name: IF702-redes-neurais
channels:
  - defaults
dependencies:
  - ca-certificates=2018.10.15
  - certifi=2018.10.15
  - freetype=2.8.1
  - grpcio=1.16.0
  - hdf5=1.10.2
  - icu=58.2
  - imbalanced-learn=0.4.3
  - jpeg=9b
  - libgpuarray=0.7.6
  - libpng=1.6.34
  - libprotobuf=3.5.2
  - libsodium=1.0.16
  - markupsafe=1.1.0
  - matplotlib=2.2.2
  - mistune=0.8.4
  - openssl=1.0.2p
  - protobuf=3.5.2
  - python=3.6.6
  - qt=5.6.2
  - sqlite=3.22.0
  - tensorboard=1.9.0
  - tensorflow=1.9.0
  - vc=14
  - yaml=0.1.7
  - zeromq=4.2.5
  - zlib=1.2.11
  - _tflow_select=2.2.0
  - absl-py=0.6.1
  - astor=0.7.1
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.0.2
  - colorama=0.4.0
  - cycler=0.10.0
  - decorator=4.3.0
  - entrypoints=0.2.3
  - gast=0.2.0
  - h5py=2.8.0
  - icc_rt=2017.0.4
  - intel-openmp=2019.0
  - ipykernel=5.1.0
  - ipython=7.1.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - jedi=0.13.1
  - jinja2=2.10
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.2.3
  - jupyter_console=6.0.0
  - jupyter_core=4.4.0
  - keras=2.2.4
  - keras-applications=1.0.6
  - keras-base=2.2.4
  - keras-preprocessing=1.0.5
  - kiwisolver=1.0.1
  - libpython=2.1
  - mako=1.0.7
  - markdown=3.0.1
  - mkl=2019.0
  - mkl-service=1.1.2
  - mkl_fft=1.0.6
  - mkl_random=1.0.1
  - msys2-conda-epoch=20160418
  - nb_conda=2.2.1
  - nb_conda_kernels=2.2.0
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - notebook=5.7.1
  - numpy=1.15.4
  - numpy-base=1.15.4
  - pandas=0.23.4
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.3.1
  - pickleshare=0.7.5
  - pip=18.1
  - prometheus_client=0.4.2
  - prompt_toolkit=2.0.7
  - pygments=2.2.0
  - pygpu=0.7.6
  - pyparsing=2.3.0
  - pyqt=5.6.0
  - python-dateutil=2.7.5
  - pytz=2018.7
  - pywinpty=0.5.4
  - pyyaml=3.13
  - pyzmq=17.1.2
  - qtconsole=4.4.2
  - scikit-learn=0.20.0
  - scipy=1.1.0
  - send2trash=1.5.0
  - setuptools=40.6.2
  - sip=4.19.8
  - six=1.11.0
  - tensorflow-base=1.9.0
  - termcolor=1.1.0
  - terminado=0.8.1
  - testpath=0.4.2
  - theano=1.0.3
  - tornado=5.1.1
  - traitlets=4.3.2
  - vs2015_runtime=14.15.26706
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.14.1
  - wheel=0.32.2
  - widgetsnbextension=3.4.2
  - wincertstore=0.2
  - winpty=0.4.3
  - pip:
    - astetik==1.9.5
    - chances==0.1.1
    - chardet==3.0.4
    - geonamescache==1.0.1
    - idna==2.7
    - kerasplotlib==0.1.4
    - patsy==0.5.1
    - requests==2.20.1
    - seaborn==0.9.0
    - statsmodels==0.9.0
    - talos==0.4.3
    - tqdm==4.28.1
    - urllib3==1.24.1
    - wrangle==0.3.1
